name: Afk
version: 1.0.0
author: Annwan
main: me.annwan.afkPlug.AfkPlug
commands:
  toggleafk:
    description: Toogles your afk status
    usage: /toggleafk, /afk
    aliases:
      - afk
api-version: 1.16